---
title: "Zika_Overview.rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Zika Virus Overview
  
  The Zika virus is spread primarily by the bite of an infected *Aedes* species mosquito, but can also be transmitted from a pregnant woman to her fetus, through sex, and through blood transfusions. 
  
**Symptoms**
  
  Most people infected with Zika won't show symptoms, but the most common symptoms of Zika are: fever, rash, headache, joint pain, red eyes, and muscle pain. Sympotoms can last for several days to weeks, but are rarely fatal. Individuals with Zika usually do not requrie hospitalization and once they have been infected, are likely to be protected from future infections. 
  
**Risk**
 
  The biggest risk of the Zika virus is that infection during pregnancy can cause a birth defect called [microcephaly][id]. and other severe brain defects in the fetus. [Guillain-Barre syndrome][id2]. an uncommon sickness of the nervous system has also been reported in areas affected by Zika.Finally, Zika has also been linked to other problems such as miscarriage, stillbirth, and other birth defects. 
  
**Treatment/Prevention**
 
  Although there is no vaccine for Zika, the best way to prevent diseases spread by mosquitos is to protect yourself and your loved ones from mosquito bites. Wearing long-sleeved clothing and long pants lessens the area that a mosquito can bite. Use insect repellents approved by the Environmental Protection Agency (EPA) and follow the labelled product instructions. Stay in shelters from mosquitos, such as indoors or screened in areas. And finally prevent sexual transmission of Zika by using condoms or not having sex.  

[id]: https://www.cdc.gov/ncbddd/birthdefects/microcephaly.html
[id2]: https://www.cdc.gov/zika/healtheffects/gbs-qa.html

